### ISSUE TITLE
TightOCR vs. Pytesseract

### ISSUE THREAD

**Issue by mettinger** [dsoprea/TightOCR#7]
I am currently using pytesseract to use tesseract from Python in a speed-critical application where I am trying to do OCR on millions of images per day.  Pytesseract works well but is rather slow, perhaps because it writes the image to disk before calling the tesseract executable.

I recently found your project, tightOCR/Ctesseract and was wondering if you had any opinion on how fast tightOCR is compared to pytesseract?

**Comment by dsoprea** [comment]
CTesseract is a C wrapper around Tesseract, which is a C++ library (C++
doesn't have a prescribed standard for how it should name the exports for
methods, so you can't bind to them off the library without using another
tool to facilitate and I didn't want the complexity to spiral out of
control). PyTesseract then wraps CTesseract.

Assuming you're allowing a reasonable amount of time for the OCR process,
what's your interpretation of "slow"?

Since I have never tested it at that scale nor do I have access to a
dataset that large,  you're probably going to have to profile the execution
and show me the time breakdowns. If we can make things better on our side,
whether in Python or C, then we will. If it's in Tesseract, then you'll
obviously have to deal with Google.

**Comment by dsoprea** [comment]
Reopen if you wanted to keep the discussion going.
